server:
  host: "0.0.0.0"
  port: 8080

database:
  driver: "sqlite"
  dsn: "/www/wwwroot/blog-backend/data/blog.db" # 生产环境数据库

content:
  # 注意：这里要改成服务器上实际存放博客内容的绝对路径
  repo_dir: "/www/wwwroot/personal-blog-content/blogs" 

app:
  name: "blog-backend-prd"
  environment: "prd"